version: '2'
services:
  php:
    image: silintl/php7
    restart: always
    volumes:
      - ./docker/cake.conf:/etc/apache2/sites-enabled/cake.conf
      - .:/var/www/cake
    ports:
      - "80:80"
    


